export enum Errors {
  MAX_PLAYERS_REACHED = "MAX_PLAYERS_REACHED",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  PLAYER_ALREADY_EXISTS = "PLAYER_ALREADY_EXISTS",
  INVALID_QUEUING_METHOD = "INVALID_QUEUING_METHOD",
  CURRENT_PLAYER_FAULT = "CURRENT_PLAYER_FAULT",
  NO_PLAYERS = "NO_PLAYERS",
}
