export enum Errors {
  MAX_PLAYERS_REACHED = "MAX_PLAYERS_REACHED",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  PLAYER_ALREADY_EXISTS = "PLAYER_ALREADY_EXISTS",
  INVALID_QUEUING_METHOD = "INVALID_QUEUING_METHOD",
  CURRENT_PLAYER_FAULT = "CURRENT_PLAYER_FAULT",
  NO_PLAYERS = "NO_PLAYERS",
  CARD_NOT_FOUND = "CARD_NOT_FOUND",

  CARD_ON_ACTION_NOT_FOUND = "CARD_ON_ACTION_NOT_FOUND",

  CARD_REQUIRES_MORE_PARAMS = "CARD_REQUIRES_MORE_PARAMS",

  NOT_PLAYER_TURN = "NOT_PLAYER_TURN",
  HAND_FAULT = "HAND_FAULT",
}
