export enum Errors {
  MAX_PLAYERS_REACHED = "MAX_PLAYERS_REACHED",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  PLAYERS_MUST_BE_UNIQUE = "PLAYERS_MUST_BE_UNIQUE",
  INVALID_QUEUING_METHOD = "INVALID_QUEUING_METHOD",
  CURRENT_PLAYER_FAULT = "CURRENT_PLAYER_FAULT",
  NO_PLAYERS = "NO_PLAYERS",
  CARD_NOT_FOUND = "CARD_NOT_FOUND",

  CARD_ON_ACTION_NOT_FOUND = "CARD_ON_ACTION_NOT_FOUND",

  CARD_REQUIRES_MORE_PARAMS = "CARD_REQUIRES_MORE_PARAMS",

  NOT_PLAYER_TURN = "NOT_PLAYER_TURN",
  HAND_FAULT = "HAND_FAULT",
  INVALID_PLAYERS_AMOUNT = "INVALID_PLAYERS_AMOUNT",
  PLAYER_MUST_BE_ALIVE = "PLAYER_MUST_BE_ALIVE",
  LEVEL_MUST_BE_NUMBER = "LEVEL_MUST_BE_NUMBER",
  INVALID_LEVEL = "INVALID_LEVEL",
  CORUPTED_SIGNAL = "CORUPTED_SIGNAL",
  PLAYER_CANT_USE_THEIR_SELF = "PLAYER_CANT_USE_THEIR_SELF",
  PROTECTED_TARGET = "PROTECTED_TARGET",
  GUARD_CANT_GUESS_ANOTHER_GUARD = "GUARD_CANT_GUESS_ANOTHER_GUARD",
  PLAYER_IS_PROTECTED = "PLAYER_IS_PROTECTED",
  FLLATTERY_NOT_TARGETED = "FLLATTERY_NOT_TARGETED",
}
